Rename vendor name and make module compatible with php ^8.1
dssjignesh/m2-fbpixel pull request #1
Opened 2024-08-06 13:30 UTC by harshdss

Rename vendor name and make module compatible with php ^8.1

2024-08-06 13:37 UTC, dssjignesh requested changes

2024-08-06 13:37 UTC, dssjignesh commented on app/code/Dss/FacebookPixel/view/frontend/web/js/subscribe.js
> +], function (jQuery, ko, Component, customerData) {
@harshdss use $ instead

2024-08-06 13:37 UTC, dssjignesh commented on app/code/Dss/FacebookPixel/view/frontend/templates/code.phtml
> +$AddToWishlist = $block->getAddToWishList();
@harshdss  please use standard variable name

2024-08-06 13:37 UTC, dssjignesh commented on app/code/Dss/FacebookPixel/etc/adminhtml/system.xml
> +    <section id="dss_facebook_pixel" translate="label" type="text" sortOrder="100"
@harshdss please format correctly

2024-08-09 12:30 UTC, harishmk1805 approved these changes

2024-08-09 12:32 UTC, harishmk1805 approved these changes

2024-08-09 12:37 UTC, dssjignesh approved these changes

2024-08-09 12:37 UTC, merged